# Generated by Django 4.2.3 on 2023-07-09 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Requerimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre requerimiento')),
                ('hecho', models.BooleanField(default=False, verbose_name='Hecho')),
            ],
        ),
    ]
