# Generated by Django 4.2.1 on 2023-07-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requerimientos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/requerimientos/%Y/%m/', verbose_name='Mockup requerimiento'),
        ),
    ]
