# Generated by Django 4.2.1 on 2023-07-13 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_requerimientos_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mockups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(verbose_name='Numero del mockup')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='blogs/mockups/%Y/%m/', verbose_name='Mockup')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre mockup')),
                ('hecho', models.BooleanField(default=False, verbose_name='Hecho')),
            ],
        ),
    ]
