# Generated by Django 4.2.1 on 2023-07-13 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_mockups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mockups',
            name='numero',
        ),
    ]
