# Generated by Django 4.2.1 on 2023-07-14 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_remove_mockups_numero'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mockups',
        ),
    ]
