# Generated by Django 4.2.1 on 2023-07-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_blogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='imagen',
            field=models.ImageField(default=0, upload_to='blogs/%Y/%m/', verbose_name='Imagen'),
            preserve_default=False,
        ),
    ]
