# Generated by Django 4.2.1 on 2023-07-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_blogs_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='slug',
            field=models.CharField(default=0, max_length=100, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
