# Generated by Django 4.2.1 on 2023-07-14 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_blogs_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogs',
            options={'verbose_name': 'Blog', 'verbose_name_plural': 'Blogs'},
        ),
        migrations.AlterModelOptions(
            name='requerimientos',
            options={'verbose_name': 'Requerimiento', 'verbose_name_plural': 'Requerimientos'},
        ),
    ]
