# Generated by Django 4.2.1 on 2023-07-14 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_alter_blogs_options_alter_requerimientos_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='slug',
            field=models.CharField(max_length=100, unique=True, verbose_name='Slug'),
        ),
    ]
