# Generated by Django 4.2.3 on 2023-07-07 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('espacioGb', models.IntegerField()),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Dispositivo',
                'verbose_name_plural': 'Dispositivos',
            },
        ),
        migrations.CreateModel(
            name='Favoritos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Favorito',
                'verbose_name_plural': 'Favoritos',
            },
        ),
        migrations.CreateModel(
            name='Favoritos_UrlJuegos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Favorito_urlJuego',
                'verbose_name_plural': 'Favoritos_urlJuegos',
            },
        ),
        migrations.CreateModel(
            name='Graficas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nucleos', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Grafica',
                'verbose_name_plural': 'Graficas',
            },
        ),
        migrations.CreateModel(
            name='GraficasGb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gb', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
            options={
                'verbose_name': 'Grafica gb',
                'verbose_name_plural': 'Graficas gb',
            },
        ),
        migrations.CreateModel(
            name='GraficasVelocidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('velocidadMhz', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Grafica velocidad',
                'verbose_name_plural': 'Graficas velocidades',
            },
        ),
        migrations.CreateModel(
            name='Historiales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busqueda', models.CharField(max_length=100)),
                ('fechaBusqueda', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Historial',
                'verbose_name_plural': 'Historiales',
            },
        ),
        migrations.CreateModel(
            name='Procesadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nucleos', models.IntegerField(blank=True, null=True)),
                ('hilos', models.IntegerField(blank=True, null=True)),
                ('mhz', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Procesador',
                'verbose_name_plural': 'Procesadores',
            },
        ),
        migrations.CreateModel(
            name='Rams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gb', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Ram',
                'verbose_name_plural': 'Rams',
            },
        ),
        migrations.CreateModel(
            name='RamsVelocidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('velocidadMhz', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Ram Velocidad',
                'verbose_name_plural': 'Rams Velocidades',
            },
        ),
        migrations.CreateModel(
            name='SistemasOperativos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Sistema Operativo',
                'verbose_name_plural': 'Sistema Operativos',
            },
        ),
        migrations.CreateModel(
            name='Telefonos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroTelefono', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Telefono',
                'verbose_name_plural': 'Telefonos',
            },
        ),
        migrations.CreateModel(
            name='TipoRam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Tipo ram',
                'verbose_name_plural': 'Tipos rams',
            },
        ),
        migrations.CreateModel(
            name='UrlJuegos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('nombreJuego', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Url Juego',
                'verbose_name_plural': 'Url Juegos',
            },
        ),
    ]
