# Generated by Django 4.2.1 on 2023-08-04 01:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favoritos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Favorito',
                'verbose_name_plural': 'Favoritos',
            },
        ),
        migrations.CreateModel(
            name='Graficas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('nucleos', models.IntegerField(blank=True, null=True, verbose_name='Nucleos')),
            ],
            options={
                'verbose_name': 'Grafica',
                'verbose_name_plural': 'Graficas',
            },
        ),
        migrations.CreateModel(
            name='GraficasGb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gb', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Espacio gb')),
            ],
            options={
                'verbose_name': 'Grafica gb',
                'verbose_name_plural': 'Graficas gb',
            },
        ),
        migrations.CreateModel(
            name='GraficasVelocidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('velocidadMhz', models.IntegerField(verbose_name='Velocidad mhz')),
            ],
            options={
                'verbose_name': 'Grafica velocidad',
                'verbose_name_plural': 'Graficas velocidades',
            },
        ),
        migrations.CreateModel(
            name='Procesadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('nucleos', models.IntegerField(blank=True, null=True, verbose_name='Nucleos')),
                ('hilos', models.IntegerField(blank=True, null=True, verbose_name='Hilos')),
                ('mhz', models.IntegerField(blank=True, null=True, verbose_name='Potencia Mhz')),
            ],
            options={
                'verbose_name': 'Procesador',
                'verbose_name_plural': 'Procesadores',
            },
        ),
        migrations.CreateModel(
            name='RamsVelocidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('velocidadMhz', models.IntegerField(verbose_name='Velocidad Mhz')),
            ],
            options={
                'verbose_name': 'Ram Velocidad',
                'verbose_name_plural': 'Rams Velocidades',
            },
        ),
        migrations.CreateModel(
            name='SistemasOperativos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Sistema Operativo',
                'verbose_name_plural': 'Sistema Operativos',
            },
        ),
        migrations.CreateModel(
            name='TipoRam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10, verbose_name='Tipo ram')),
            ],
            options={
                'verbose_name': 'Tipo ram',
                'verbose_name_plural': 'Tipos rams',
            },
        ),
        migrations.CreateModel(
            name='Telefonos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroTelefono', models.CharField(max_length=20, verbose_name='Numero de telefono')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Telefono',
                'verbose_name_plural': 'Telefonos',
            },
        ),
        migrations.CreateModel(
            name='Rams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gb', models.IntegerField(verbose_name='Espacio gb')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispositivos.tiporam', verbose_name='Tipo ram')),
                ('velocidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dispositivos.ramsvelocidades', verbose_name='Velocidad')),
            ],
            options={
                'verbose_name': 'Ram',
                'verbose_name_plural': 'Rams',
            },
        ),
        migrations.CreateModel(
            name='Juegos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Nombre')),
                ('urlPagina', models.URLField(verbose_name='Url pagina')),
                ('espacio', models.IntegerField(verbose_name='Espacio necesario')),
                ('promedioPotencia', models.IntegerField(blank=True, null=True, verbose_name='Promedio potencia')),
                ('grafica', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dispositivos.graficas', verbose_name='Grafica')),
                ('procesador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dispositivos.procesadores', verbose_name='Procesador')),
                ('ram', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dispositivos.rams', verbose_name='Ram')),
            ],
        ),
        migrations.CreateModel(
            name='Historiales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busqueda', models.CharField(max_length=100, verbose_name='Busqueda')),
                ('fechaBusqueda', models.DateField(auto_now_add=True, verbose_name='Fecha de busqueda')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Historial',
                'verbose_name_plural': 'Historiales',
            },
        ),
        migrations.AddField(
            model_name='graficas',
            name='gb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dispositivos.graficasgb', verbose_name='Espacio gb'),
        ),
        migrations.AddField(
            model_name='graficas',
            name='velocidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dispositivos.graficasvelocidades', verbose_name='Velocidad'),
        ),
        migrations.CreateModel(
            name='Favoritos_UrlJuegos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispositivos.favoritos', verbose_name='Favorito')),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispositivos.juegos', verbose_name='Juego')),
            ],
            options={
                'verbose_name': 'Favorito_juego',
                'verbose_name_plural': 'Favoritos_juegos',
            },
        ),
        migrations.CreateModel(
            name='Dispositivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('espacioGb', models.IntegerField(verbose_name='Espacio gb')),
                ('nombre', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre')),
                ('promedioPotencia', models.IntegerField(blank=True, null=True, verbose_name='Promedio potencia')),
                ('grafica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispositivos.graficas', verbose_name='Grafica')),
                ('procesador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispositivos.procesadores', verbose_name='Procesador')),
                ('ram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispositivos.rams', verbose_name='Ram')),
                ('sistemaOperativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispositivos.sistemasoperativos', verbose_name='Sistema operativo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Dispositivo',
                'verbose_name_plural': 'Dispositivos',
            },
        ),
    ]
