# Generated by Django 4.2.1 on 2023-08-07 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dispositivos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='telefonos',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='rams',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispositivos.tiporam', verbose_name='Tipo ram'),
        ),
        migrations.AddField(
            model_name='rams',
            name='velocidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dispositivos.ramsvelocidades', verbose_name='Velocidad'),
        ),
        migrations.AddField(
            model_name='juegos',
            name='grafica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dispositivos.graficas', verbose_name='Grafica'),
        ),
        migrations.AddField(
            model_name='juegos',
            name='procesador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dispositivos.procesadores', verbose_name='Procesador'),
        ),
        migrations.AddField(
            model_name='juegos',
            name='ram',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dispositivos.rams', verbose_name='Ram'),
        ),
        migrations.AddField(
            model_name='historiales',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='graficas',
            name='gb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dispositivos.graficasgb', verbose_name='Espacio gb'),
        ),
        migrations.AddField(
            model_name='graficas',
            name='velocidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dispositivos.graficasvelocidades', verbose_name='Velocidad'),
        ),
        migrations.AddField(
            model_name='favoritos_urljuegos',
            name='favorito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispositivos.favoritos', verbose_name='Favorito'),
        ),
        migrations.AddField(
            model_name='favoritos_urljuegos',
            name='juego',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispositivos.juegos', verbose_name='Juego'),
        ),
        migrations.AddField(
            model_name='favoritos',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='dispositivos',
            name='grafica',
            field=models.ManyToManyField(to='dispositivos.graficas', verbose_name='Grafica'),
        ),
        migrations.AddField(
            model_name='dispositivos',
            name='procesador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dispositivos.procesadores', verbose_name='Procesador'),
        ),
        migrations.AddField(
            model_name='dispositivos',
            name='ram',
            field=models.ManyToManyField(to='dispositivos.rams', verbose_name='Ram'),
        ),
        migrations.AddField(
            model_name='dispositivos',
            name='sistemaOperativo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dispositivos.sistemasoperativos', verbose_name='Sistema operativo'),
        ),
        migrations.AddField(
            model_name='dispositivos',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
