# Generated by Django 4.2.1 on 2023-08-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juegos',
            name='espacio',
            field=models.IntegerField(verbose_name='Espacio necesario en gb'),
        ),
    ]
