# Generated by Django 4.2.1 on 2023-08-07 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivos',
            name='procesador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dispositivos.procesadores', verbose_name='Procesador'),
        ),
        migrations.AlterField(
            model_name='dispositivos',
            name='sistemaOperativo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dispositivos.sistemasoperativos', verbose_name='Sistema operativo'),
        ),
    ]
