# Generated by Django 4.2.1 on 2023-08-11 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0003_alter_dispositivos_procesador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivos',
            name='json',
            field=models.JSONField(blank=True, null=True, verbose_name='Json presentación'),
        ),
    ]
