# Generated by Django 4.2.1 on 2023-08-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0004_dispositivos_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivos',
            name='nombre',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre'),
        ),
    ]
