# Generated by Django 4.2.1 on 2023-08-31 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0004_favoritos_juego_delete_favoritos_urljuegos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='juegos',
            options={'verbose_name': 'Juego', 'verbose_name_plural': 'Juegos'},
        ),
        migrations.AddField(
            model_name='juegos',
            name='cantidadVisitas',
            field=models.IntegerField(default=0, verbose_name='Cantidad visitas'),
            preserve_default=False,
        ),
    ]
