# Generated by Django 4.2.1 on 2023-08-31 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0005_alter_juegos_options_juegos_cantidadvisitas'),
    ]

    operations = [
        migrations.AddField(
            model_name='juegos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='users/%Y/%m/', verbose_name='Imagen juego'),
        ),
    ]
