# Generated by Django 4.2.1 on 2023-09-01 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0007_juegos_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juegos',
            name='descripcion',
            field=models.CharField(max_length=500, verbose_name='Descripción'),
        ),
    ]
