# Generated by Django 4.2.1 on 2023-09-01 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0008_alter_juegos_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='juegos',
            name='slug',
            field=models.CharField(default='holi', max_length=200, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
