# Generated by Django 4.2.1 on 2023-09-01 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0010_alter_juegos_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juegos',
            name='slug',
            field=models.CharField(default='juego', max_length=200, unique=True, verbose_name='Slug'),
        ),
    ]
