# Generated by Django 4.2.1 on 2023-09-01 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0011_alter_juegos_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juegos',
            name='cantidadVisitas',
            field=models.IntegerField(default=0, verbose_name='Cantidad visitas'),
        ),
    ]
