# Generated by Django 4.2.1 on 2023-09-03 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0012_alter_juegos_cantidadvisitas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juegos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagen/%Y/%m/', verbose_name='Imagen juego'),
        ),
        migrations.CreateModel(
            name='ImagenesJuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes_juegos/%Y/%m/', verbose_name='Imagen')),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispositivos.juegos')),
            ],
        ),
    ]
