# Generated by Django 4.2.1 on 2023-09-06 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0017_alter_favoritos_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritos',
            name='juegos',
            field=models.ManyToManyField(blank=True, null=True, to='dispositivos.juegos'),
        ),
    ]
