# Generated by Django 4.2.1 on 2023-09-16 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0019_alter_favoritos_juegos'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivos',
            name='ram_re',
            field=models.BooleanField(default=False),
        ),
    ]
